name: Deploy to Staging

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@52.66.241.104 << 'EOF'
            cd ci-cd_prac
            git pull origin dev

            source ~/.nvm/nvm.sh && nvm use 22

            npm install -g pm2 pnpm
            pnpm install
            pnpm run build

            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server
          EOF
