name: Deploy to staging
on:
  push:
    branches: [ main ]
jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - name: Configure SSH
        run: |
          # Create .ssh directory
          mkdir -p ~/.ssh
          
          # Add private key with proper formatting
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Add known hosts
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@64.227.147.124 '
            cd week-25-ci-next-app/ && \
            git pull origin main && \
            export PATH=/root/.nvm/versions/node/v22.13.1/bin:$PATH && \
            npm install -g pnpm && \
            pnpm install && \
            pnpm run build && \
            pm2 restart fe-sever && \
            pm2 restart http-sever && \
            pm2 restart ws-sever
          '