name: Deploy to staging
on:
  push:
    branches: [ dev ]
jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 52.66.241.104 >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@52.66.241.104 '
            cd ci-cd_prac/ && \
            git pull origin dev && \
            export PATH=/root/.nvm/versions/node/v22.13.1/bin:$PATH && \
            npm install -g pnpm && \
            pnpm install && \
            pnpm run build && \
            pm2 restart fe-sever && \
            pm2 restart http-sever && \
            pm2 restart ws-sever
          '