name: Deploy to staging
on:
  push:
    branches: [ dev ]
jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - name: Configure SSH
        run: |
          # Debug: Print first few characters of key to verify format (safely)
          echo "First line of key:"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -n 1
          
          # Create .ssh directory
          mkdir -p ~/.ssh
          
          # Write key directly without base64 decode
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          
          # Ensure correct permissions
          chmod 600 ~/.ssh/id_rsa
          
          # Debug: Check key file exists and permissions
          ls -la ~/.ssh/id_rsa
          
          # Add server to known hosts
          ssh-keyscan -H 52.66.241.104 >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          # Try connection with verbose logging
          ssh -vvv -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@52.66.241.104 'echo "test"'